### ISSUE TITLE
Start time to show on agenda

### ISSUE THREAD

**Issue by key30wp** [Revln9/react-agenda#6]
Hello, I would like to know how to make the component start and end on a specific time, I thought "startDate" parameter would work for it but it didnt, so is there another way to make my agenda starts at 7am ?

**Comment by Revln9** [comment]
Hi , if i understand correctly you want the first row of the agenda to be at 7am ? this was planned but unfortunately still not implemented (lack of time) ,  i apologize for that , but you can  do it by changing manually one line of code and rebuilding the module by yourself 
https://github.com/Revln9/react-agenda/blob/0b1ba2fd2848590a1b927157420e4265eeefb415/src/reactAgenda.js#L113

change it to 
`
rows.push(moment(this.state.date).hours(7).minutes(0).seconds(0).milliseconds(0).add(Math.floor(i * interval), 'minutes'));
`

i will push an update soon and implement this feature as a property , so stay tuned , in the meantime , i hope it helps ^^

**Comment by key30wp** [comment]
That would a excellent improvement! thanks for your solution!

**Comment by key30wp** [comment]
Do I need to run something after this on the react-agenda directory?

**Comment by Revln9** [comment]
Yes , you need to rebuild the minified version
in the  react-agenda directory type
 `npm run build` 

and you are good to go.

update is coming this weekend

**Comment by revskill10** [comment]
I'd love to have options to specify the range of hour per day i'll show.
For example, in my case, i want to show from 6AM to 9PM only.

**Comment by Revln9** [comment]
new version available that lets you specify  the range of hour per day , check it out.
Regards
