### ISSUE TITLE
Collision detection ?

### ISSUE THREAD

**Issue by revskill10** [Revln9/react-agenda#7]
Is there any plan to provide options like `collisiontDetection={true}` for agenda ? So that when user create an event with collision time range with other events, it'll show a warning.

**Comment by Revln9** [comment]
Hi , good suggestion you have here, i'll try to give it a shot after i deal with some urgent fixes, related here: https://github.com/Revln9/react-agenda/issues/8

if you want to add something, feel free to comment. 
Thank you!
